### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by ndushay** [comment]
do you want to rebase with my mods?  I did some gemfile cleanup this morning before this was here ...  sorry.

**Comment by ndushay** [comment]
also, i'm not convinced this app actually uses the db;  it's also a bit weird that sqlite and mysql are both in the default group ...

**Comment by cbeer** [comment]
Rebased. I agree that we don't seem to use the database and what we're doing it weird, although I suspect removing the activerecord dependency may be non-trivial and not worth the effort. Certainly, though, if we don't care about the database, we oughtn't pin particular gem versions.

**Comment by ndushay** [comment]
I actually was working on removing the activerecord dependency this morning, but laney felt we should may have a more coherent approach to simplifying all of this stanford-sync code, so my efforts are just sitting on a local branch.

**Pull request merged**
